version: '3'
services:
  app:
    image: myjenkins-blueocean:2.401.2-1
    container_name: jenkins
    restart: always
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ./jenkins_data/:/var/jenkins_home/
    
